import wx
import os
import wx.lib.scrolledpanel as scrolled

dirName = os.path.dirname(os.path.abspath(__file__))
bitmapDir = os.path.join(dirName, 'bitmaps')
class PackagePanel(wx.Panel):
    def __init__(self,parent,size,data):
        if size=="BIG":
            self.size = (180,180)
        elif size == "MIDDLE":
            self.size = (150,150)
        else:
            self.size = (120,120)
        wx.Panel.__init__(self, parent, size=self.size)
        self.data = data
        self.frame = wx.StaticBox(self,label=data[0],size=(10,10))
        hbox =wx.BoxSizer()
        hbox.Add(self.frame,1,wx.EXPAND)
        self.SetSizer(hbox)

class PackageDialog(wx.Dialog):
    def __init__(self, parent, log, orderID, size=wx.DefaultSize, pos=wx.DefaultPosition,
                 style=wx.DEFAULT_DIALOG_STYLE):
        wx.Dialog.__init__(self)
        self.orderID = orderID
        self.log = log
        self.parent = parent
        # self.log.WriteText("操作员：'%s' 开始执行库存参数设置操作。。。\r\n"%(self.parent.operator_name))
        self.SetExtraStyle(wx.DIALOG_EX_METAL)
        self.Create(parent, -1, "产品打包操作对话框", pos, size, style)
        sizer = wx.BoxSizer(wx.VERTICAL)
        panel = wx.Panel(self, -1, size=(1800, 900))
        vbox = wx.BoxSizer(wx.VERTICAL)
        vbox.Add((-1, 20))
        hbox = wx.BoxSizer()
        hbox.Add(10, -1)
        hbox.Add(wx.StaticText(panel, label='订单号：'), 0, wx.TOP, 5)
        self.orderIDTXT = wx.TextCtrl(panel, size=(50, 25), style=wx.TE_READONLY)
        self.orderIDTXT.SetValue('%05d' % int(self.orderID))
        hbox.Add(self.orderIDTXT, 1, wx.LEFT | wx.RIGHT, 10)
        vbox.Add(hbox, 0, wx.EXPAND)

        self.finishPackagePanel = scrolled.ScrolledPanel(panel,size=(100,200))
        vbox.Add(self.finishPackagePanel,0,wx.EXPAND|wx.LEFT|wx.RIGHT|wx.TOP,10)
        hhbox = wx.BoxSizer()
        hhbox.Add((10,-1))
        self.leftWorkingPackagePanel = wx.Panel(panel,size=(100,100))
        hhbox.Add(self.leftWorkingPackagePanel,1,wx.EXPAND)
        self.middleControlPanel = wx.Panel(panel,size=(50,-1))
        self.middleControlPanel.SetBackgroundColour(wx.Colour(220,220,220))
        hhbox.Add(self.middleControlPanel,0,wx.EXPAND)
        self.rightWorkingPackagePanel = wx.Panel(panel,size=(100,100))
        hhbox.Add(self.rightWorkingPackagePanel,1,wx.EXPAND)
        hhbox.Add((10,-1))
        vbox.Add(hhbox,1,wx.EXPAND)
        self.bottomPackagePanel = scrolled.ScrolledPanel(panel,size=(100,200))
        vbox.Add(self.bottomPackagePanel,0,wx.EXPAND|wx.LEFT|wx.RIGHT|wx.BOTTOM,10)
        panel.SetSizer(vbox)

        vvbox=wx.BoxSizer(wx.VERTICAL)
        hhbox = wx.BoxSizer()
        self.leftTopDownloadBTN = wx.Button(self.leftWorkingPackagePanel,label="▼",size=(100,50))
        self.leftTopUploadBTN = wx.Button(self.leftWorkingPackagePanel,label="▲",size=(100,50))
        hhbox.Add(self.leftTopDownloadBTN,1)
        hhbox.Add(self.leftTopUploadBTN,1)
        vvbox.Add(hhbox,0,wx.EXPAND)
        hhbox = wx.BoxSizer()
        self.leftFrontViewPanel = wx.Panel(self.leftWorkingPackagePanel,size=(100,100))
        self.leftTopViewPanel = wx.Panel(self.leftWorkingPackagePanel,size=(100,100))
        hhbox.Add(self.leftFrontViewPanel,1,wx.EXPAND)
        hhbox.Add(self.leftTopViewPanel,1,wx.EXPAND)
        vvbox.Add(hhbox,1,wx.EXPAND)
        hhbox = wx.BoxSizer()
        self.leftBottomDownloadBTN = wx.Button(self.leftWorkingPackagePanel,label="▼",size=(100,50))
        self.leftBottonUploadBTN = wx.Button(self.leftWorkingPackagePanel,label="▲",size=(100,50))
        hhbox.Add(self.leftBottomDownloadBTN,1)
        hhbox.Add(self.leftBottonUploadBTN,1)
        vvbox.Add(hhbox,0,wx.EXPAND)
        self.leftWorkingPackagePanel.SetSizer(vvbox)

        vvbox=wx.BoxSizer(wx.VERTICAL)
        hhbox = wx.BoxSizer()
        self.rightTopDownloadBTN = wx.Button(self.rightWorkingPackagePanel,label="▼",size=(100,50))
        self.rightTopUploadBTN = wx.Button(self.rightWorkingPackagePanel,label="▲",size=(100,50))
        hhbox.Add(self.rightTopDownloadBTN,1)
        hhbox.Add(self.rightTopUploadBTN,1)
        vvbox.Add(hhbox,0,wx.EXPAND)
        hhbox = wx.BoxSizer()
        self.rightFrontViewPanel = wx.Panel(self.rightWorkingPackagePanel,size=(100,100))
        self.rightTopViewPanel = wx.Panel(self.rightWorkingPackagePanel,size=(100,100))
        hhbox.Add(self.rightFrontViewPanel,1,wx.EXPAND)
        hhbox.Add(self.rightTopViewPanel,1,wx.EXPAND)
        vvbox.Add(hhbox,1,wx.EXPAND)
        hhbox = wx.BoxSizer()
        self.rightBottomDownloadBTN = wx.Button(self.rightWorkingPackagePanel,label="▼",size=(100,50))
        self.rightBottonUploadBTN = wx.Button(self.rightWorkingPackagePanel,label="▲",size=(100,50))
        hhbox.Add(self.rightBottomDownloadBTN,1)
        hhbox.Add(self.rightBottonUploadBTN,1)
        vvbox.Add(hhbox,0,wx.EXPAND)
        self.rightWorkingPackagePanel.SetSizer(vvbox)

        self.middleLeftAddBTN = wx.Button(self.middleControlPanel,label="<<+",size=(10,50))
        self.middleRightAddBTN = wx.Button(self.middleControlPanel,label="+>>",size=(10,50))
        self.middleLeftBTN = wx.Button(self.middleControlPanel,label=">>",size=(10,20))
        self.middleRightBTN = wx.Button(self.middleControlPanel,label="<<",size=(10,20))
        vvbox = wx.BoxSizer(wx.VERTICAL)
        vvbox.Add(self.middleLeftAddBTN,0,wx.EXPAND)
        vvbox.Add(self.middleRightBTN,1,wx.EXPAND)
        vvbox.Add(self.middleLeftBTN,1,wx.EXPAND)
        vvbox.Add(self.middleRightAddBTN,0,wx.EXPAND)
        self.middleControlPanel.SetSizer(vvbox)

        hbox=wx.BoxSizer()
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘1"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘2"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘3"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘4"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"MIDDLE",["货盘5"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘6"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘7"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘8"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘9"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘10"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘11"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘12"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘13"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘14"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"MIDDLE",["货盘15"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘16"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘17"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘18"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"SMALL",["货盘19"])
        hbox.Add(package1)
        package1 = PackagePanel(self.finishPackagePanel,"BIG",["货盘20"])
        hbox.Add(package1)
        self.finishPackagePanel.SetSizer(hbox)
        self.finishPackagePanel.SetAutoLayout(1)
        self.finishPackagePanel.SetupScrolling()



        # panel.SetBackgroundColour(wx.Colour(234,219,212))
        sizer.Add(panel, 0, wx.EXPAND)
        line = wx.StaticLine(self, -1, size=(30, -1), style=wx.LI_HORIZONTAL)
        sizer.Add(line, 0, wx.GROW | wx.RIGHT | wx.TOP, 5)

        btnsizer = wx.BoxSizer()
        bitmap1 = wx.Bitmap("bitmaps/ok3.png", wx.BITMAP_TYPE_PNG)
        bitmap2 = wx.Bitmap("bitmaps/cancel1.png", wx.BITMAP_TYPE_PNG)
        bitmap3 = wx.Bitmap("bitmaps/33.png", wx.BITMAP_TYPE_PNG)
        btn_ok = wx.Button(self, wx.ID_OK, "确  定", size=(200, 50))
        btn_ok.SetBitmap(bitmap1, wx.LEFT)
        btn_cancel = wx.Button(self, wx.ID_CANCEL, "取  消", size=(200, 50))
        btn_cancel.SetBitmap(bitmap2, wx.LEFT)
        btnsizer.Add(btn_ok, 0)
        btnsizer.Add((40, -1), 0)
        btnsizer.Add(btn_cancel, 0)
        sizer.Add(btnsizer, 0, wx.ALIGN_CENTER | wx.ALL, 10)
        self.SetSizer(sizer)
        sizer.Fit(self)
        # btn_ok.Bind(wx.EVT_BUTTON, self.OnOk)
        # btn_cancel.Bind(wx.EVT_BUTTON, self.OnCancel)
        # manualInputBTN.Bind(wx.EVT_BUTTON, self.OnCancel)

    # def OnOk(self, event):
    #     event.Skip()
    #
    # def OnCancel(self, event):
    #     # self.log.WriteText("操作员：'%s' 取消库存参数设置操作\r\n"%(self.parent.operator_name))
    #     event.Skip()
